#!/bin/zsh

mkdir build
cp -r include ./build
cp include.cpp ./build
cp main.cpp ./build
cd ./build
touch copy.cpp
cat ./include/*.cpp main.cpp > copy.cpp
sed -i -e  '/#include/d' copy.cpp 
cat include.cpp copy.cpp > output.cpp
g++ -std=c++17 output.cpp -o output
mv output output.cpp ../
cd ..
rm -r ./build

# curl -o ABC.html https://atcoder.jp/contests/abc155/tasks/abc155_c

